import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/app.header";
import AppFooter from "./components/app.footer";
import "nprogress/nprogress.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FPT FILM: Non-Profit Projects",
  description: "Generated by ninhpd",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div style={{ padding: "100px 0 20px 0" }}>{children}</div>
        <AppFooter />
      </body>
    </html>
  );
}
