import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/app.header";
import AppFooter from "./components/app.footer";
import styles from "./layout.module.css";
import "nprogress/nprogress.css";
import AntdStyledComponentsRegistry from "./components/AntdStyledComponentsRegistry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FPT FILM: Non-Profit Projects",
  description: "Generated by ninhpd",
  icons: {
    icon: "./favicon.ico?v=4",
    apple: "/apple-touch-icon.png?v=4",
    shortcut: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdStyledComponentsRegistry>
          <Header />
          <div className={styles.container}>{children}</div>
          <AppFooter />
        </AntdStyledComponentsRegistry>
      </body>
    </html>
  );
}
